name: Python application test with Github Actions

on:
  pull_request:
    branches: 
      - '**' # Run this workflow for PRs made to any branch
  workflow_dispatch: # Allows for manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest

    - name: Show pytest failure in PR if it occurs
      uses: actions/github-script@v3
      if: ${{ failure() }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue_number = context.issue.number;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Testes falharam! Cheque a página do Actions para mais detalhes.'
          });
