name: Deploy to App Engine

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK (dev)
        if: github.event.pull_request.base.ref == 'dev' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GAP_DEV_AUTH }}

      - name: Setup Google Cloud SDK (main)
        if: github.event.pull_request.base.ref == 'main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'main')
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GAP_PROD_AUTH }}
      
      - name: Deploy to App Engine (dev)
        if: github.event.pull_request.base.ref == 'dev' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
        run: |
          gcloud app deploy --quiet --project banks-dev-392615 app.yaml

      - name: Deploy to App Engine (main)
        if: github.event.pull_request.base.ref == 'main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'main')
        run: |
          gcloud app deploy --quiet --project banks-prod-392615 app.yaml
